# Schema for the configuration files of the statistics module.

file_download_counter.settings:
  type: config_object
  label: 'File Download settings'
  mapping:
    access_log:
      type: mapping
      label: 'Access log settings'
      mapping:
        enabled:
          type: boolean
          label: 'Enable'
        max_lifetime:
          type: integer
          label: 'Maximum lifetime'
    count_downloads:
      type: integer
      label: 'Count content downloads'
    display_max_age:
      type: integer
      label: 'How long any statistics may be cached, i.e. the refresh interval'

block.settings.file_download_counter_popular_block:
  type: block_settings
  label: 'Popular downloads block settings'
  mapping:
    top_day_num:
      type: integer
      label: 'Number of day\s top downloads to display'
    top_all_num:
      type: integer
      label: 'Number of all time downloads to display'
    top_last_num:
      type: integer
      label: 'Number of most recent downloads to display'
