# Schema for the views plugins of the File Download Counter module.

views.field.file_download_counter_numeric:
  type: views.field.numeric
  label: 'Numeric values from the file download counter module'

views.field.file_download_counter_timestamp:
  type: views.field.date
  label: 'The most recent time the file has been downloaded'
